# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ssd_server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/ssd_server.proto',
  package='ssd_server',
  serialized_pb=_b('\n\x16proto/ssd_server.proto\x12\nssd_server\"F\n\x07Request\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c\x12!\n\x14\x63onfidence_threshold\x18\x03 \x01(\x02:\x03\x30.5\"\xc2\x02\n\x08Response\x12\x37\n\x08\x62iz_code\x18\x01 \x01(\x0e\x32\x1c.ssd_server.Response.BizCode:\x07SUCCESS\x12\x11\n\terror_msg\x18\x02 \x01(\t\x12\x32\n\nbiz_result\x18\x03 \x03(\x0b\x32\x1e.ssd_server.Response.Detection\x12\x14\n\x0c\x63ompute_time\x18\x04 \x02(\x05\x12\x13\n\x0bworker_info\x18\x05 \x01(\t\x1a\x61\n\tDetection\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04prob\x18\x02 \x02(\x02\x12\x0c\n\x04left\x18\x03 \x02(\x02\x12\x0b\n\x03top\x18\x04 \x02(\x02\x12\r\n\x05right\x18\x05 \x02(\x02\x12\x0e\n\x06\x62ottom\x18\x06 \x02(\x02\"(\n\x07\x42izCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x10\n\x0cSYSTEM_ERROR\x10\x63')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_RESPONSE_BIZCODE = _descriptor.EnumDescriptor(
  name='BizCode',
  full_name='ssd_server.Response.BizCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SYSTEM_ERROR', index=1, number=99,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=393,
  serialized_end=433,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_BIZCODE)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='ssd_server.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ssd_server.Request.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='ssd_server.Request.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='confidence_threshold', full_name='ssd_server.Request.confidence_threshold', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0.5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=108,
)


_RESPONSE_DETECTION = _descriptor.Descriptor(
  name='Detection',
  full_name='ssd_server.Response.Detection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ssd_server.Response.Detection.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prob', full_name='ssd_server.Response.Detection.prob', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='left', full_name='ssd_server.Response.Detection.left', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='top', full_name='ssd_server.Response.Detection.top', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='right', full_name='ssd_server.Response.Detection.right', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bottom', full_name='ssd_server.Response.Detection.bottom', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=391,
)

_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='ssd_server.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='biz_code', full_name='ssd_server.Response.biz_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_msg', full_name='ssd_server.Response.error_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='biz_result', full_name='ssd_server.Response.biz_result', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='compute_time', full_name='ssd_server.Response.compute_time', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='worker_info', full_name='ssd_server.Response.worker_info', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RESPONSE_DETECTION, ],
  enum_types=[
    _RESPONSE_BIZCODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=433,
)

_RESPONSE_DETECTION.containing_type = _RESPONSE
_RESPONSE.fields_by_name['biz_code'].enum_type = _RESPONSE_BIZCODE
_RESPONSE.fields_by_name['biz_result'].message_type = _RESPONSE_DETECTION
_RESPONSE_BIZCODE.containing_type = _RESPONSE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'proto.ssd_server_pb2'
  # @@protoc_insertion_point(class_scope:ssd_server.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(

  Detection = _reflection.GeneratedProtocolMessageType('Detection', (_message.Message,), dict(
    DESCRIPTOR = _RESPONSE_DETECTION,
    __module__ = 'proto.ssd_server_pb2'
    # @@protoc_insertion_point(class_scope:ssd_server.Response.Detection)
    ))
  ,
  DESCRIPTOR = _RESPONSE,
  __module__ = 'proto.ssd_server_pb2'
  # @@protoc_insertion_point(class_scope:ssd_server.Response)
  ))
_sym_db.RegisterMessage(Response)
_sym_db.RegisterMessage(Response.Detection)


# @@protoc_insertion_point(module_scope)
